function createPlant(data) {
  return {
    wateringFrequency: "Water when the top 1 to 2 inches of soil feel dry.",
    humidity: "Average indoor humidity",
    petSafety: "Use caution around pets",
    difficulty: "Moderate",
    placement: "Bright room near a window",
    soil: "Well-draining indoor potting mix",
    fertilizer: "Feed once a month in spring and summer",
    temperature: "18°C to 29°C",
    ...data
  };
}

const plants = [
  createPlant({
    id: "monstera-deliciosa",
    name: "Monstera Deliciosa",
    category: "Indoor",
    light: "Bright indirect light",
    size: "Medium",
    price: 799,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Indoor%20Monstera%20deliciosa.jpg",
    description: "A sculptural tropical plant with iconic split leaves.",
    wateringFrequency: "Water when the top 1 to 2 inches feel dry, usually every 7 to 10 days.",
    humidity: "Prefers medium to high humidity",
    petSafety: "Not pet safe",
    difficulty: "Beginner friendly",
    placement: "Living rooms with bright filtered daylight",
    soil: "Chunky aroid mix with good airflow",
    fertilizer: "Feed every 4 weeks during active growth",
    temperature: "18°C to 30°C"
  }),
  createPlant({
    id: "snake-plant",
    name: "Snake Plant",
    category: "Low Maintenance",
    light: "Low to bright light",
    size: "Medium",
    price: 499,
    image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Snake_plant.jpg",
    description: "Tough, upright foliage that handles neglect well.",
    wateringFrequency: "Water only when the soil is fully dry, often every 2 to 3 weeks.",
    humidity: "Handles dry indoor air well",
    petSafety: "Not pet safe",
    difficulty: "Very easy",
    placement: "Bedrooms, hallways, and lower-light corners",
    soil: "Fast-draining succulent or cactus mix",
    fertilizer: "Feed lightly every 6 to 8 weeks in warm months",
    temperature: "16°C to 30°C"
  }),
  createPlant({
    id: "peace-lily",
    name: "Peace Lily",
    category: "Air Purifying",
    light: "Medium indirect light",
    size: "Medium",
    price: 649,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Peace%20lily.jpg",
    description: "Glossy leaves and white blooms for calm indoor corners.",
    wateringFrequency: "Keep the soil lightly moist and water when the top layer begins to dry.",
    humidity: "Enjoys higher humidity",
    petSafety: "Not pet safe",
    difficulty: "Moderate",
    placement: "Calm corners away from harsh sun",
    soil: "Moisture-retentive but well-draining mix",
    fertilizer: "Feed monthly in spring and summer",
    temperature: "18°C to 27°C"
  }),
  createPlant({
    id: "zz-plant",
    name: "ZZ Plant",
    category: "Low Maintenance",
    light: "Low to medium light",
    size: "Medium",
    price: 599,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/ZZ%20Plant%20%28Zamioculcas%20zamiifolia%29.jpg",
    description: "Shiny deep-green foliage with excellent drought tolerance.",
    wateringFrequency: "Let the soil dry out almost completely before watering.",
    humidity: "Comfortable in average indoor humidity",
    petSafety: "Not pet safe",
    difficulty: "Very easy",
    placement: "Offices and low-light rooms",
    soil: "Loose, well-draining potting mix",
    fertilizer: "Feed every 6 weeks during growth season",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "areca-palm",
    name: "Areca Palm",
    category: "Indoor",
    light: "Bright filtered light",
    size: "Large",
    price: 999,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dypsis%20lutescens%2022zz.jpg",
    description: "A soft, feathery palm that brings a fresh tropical look.",
    wateringFrequency: "Water when the top inch feels dry and avoid letting the pot fully dry out.",
    humidity: "Prefers moderate to higher humidity",
    petSafety: "Pet safe",
    difficulty: "Moderate",
    placement: "Bright living rooms with space around the leaves",
    soil: "Rich but airy indoor palm mix",
    fertilizer: "Feed once a month in spring and summer",
    temperature: "18°C to 27°C"
  }),
  createPlant({
    id: "jade-plant",
    name: "Jade Plant",
    category: "Succulent",
    light: "Bright light",
    size: "Small",
    price: 349,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Jade%20Plant.jpg",
    description: "Compact succulent with thick leaves and easy care needs.",
    wateringFrequency: "Water deeply only after the soil has gone fully dry.",
    humidity: "Happy in dry rooms",
    petSafety: "Not pet safe",
    difficulty: "Easy",
    placement: "Sunny sills and bright desks",
    soil: "Cactus mix with sharp drainage",
    fertilizer: "Feed lightly every 6 to 8 weeks",
    temperature: "18°C to 27°C"
  }),
  createPlant({
    id: "fiddle-leaf-fig",
    name: "Fiddle Leaf Fig",
    category: "Statement Plant",
    light: "Bright indirect light",
    size: "Large",
    price: 1299,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ficus%20lyrata%20200718838.jpg",
    description: "Large violin-shaped leaves for a bold living room feature.",
    wateringFrequency: "Water when the top 2 inches of soil are dry and keep the routine steady.",
    humidity: "Likes medium to high humidity",
    petSafety: "Not pet safe",
    difficulty: "Moderate",
    placement: "Bright living rooms with stable light",
    soil: "Well-draining indoor tree mix",
    fertilizer: "Feed every 4 weeks in warmer months",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "pothos",
    name: "Golden Pothos",
    category: "Hanging",
    light: "Low to bright indirect light",
    size: "Small",
    price: 399,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Epipremnum%20aureum.jpg",
    description: "Trailing vines that grow fast and adapt to many spaces.",
    wateringFrequency: "Water when the top inch or two feels dry.",
    humidity: "Flexible in average indoor humidity",
    petSafety: "Not pet safe",
    difficulty: "Very easy",
    placement: "Shelves, ledges, and hanging baskets",
    soil: "All-purpose indoor potting mix",
    fertilizer: "Feed monthly in spring and summer",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "rubber-plant",
    name: "Rubber Plant",
    category: "Indoor",
    light: "Bright filtered light",
    size: "Large",
    price: 899,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ficus%20elastica%2060623001.jpg",
    description: "Glossy broad leaves and a strong architectural silhouette.",
    wateringFrequency: "Water when the top 1 to 2 inches feel dry, then let excess drain well.",
    humidity: "Prefers moderate humidity",
    petSafety: "Not pet safe",
    difficulty: "Easy",
    placement: "Bright corners with room for upright growth",
    soil: "Well-draining potting mix",
    fertilizer: "Feed every 4 to 6 weeks in growth season",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "calathea-ornata",
    name: "Calathea Ornata",
    category: "Foliage",
    light: "Medium indirect light",
    size: "Medium",
    price: 749,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Calathea%20ornata.jpg",
    description: "Striped leaves with a dramatic pattern and soft tropical texture.",
    wateringFrequency: "Keep the soil lightly moist and never let it stay bone dry for long.",
    humidity: "Needs higher humidity",
    petSafety: "Pet safe",
    difficulty: "Advanced beginner",
    placement: "Bathrooms or humid corners away from direct sun",
    soil: "Moisture-retentive but airy mix",
    fertilizer: "Feed lightly once a month in spring and summer",
    temperature: "18°C to 27°C"
  }),
  createPlant({
    id: "string-of-pearls",
    name: "String of Pearls",
    category: "Hanging",
    light: "Bright indirect light",
    size: "Small",
    price: 459,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Senecio%20rowleyanus%20%28Curio%20rowleyanus%29.jpg",
    description: "A trailing succulent with bead-like foliage for high shelves.",
    wateringFrequency: "Wait for the soil to dry fully before watering again.",
    humidity: "Prefers drier air",
    petSafety: "Not pet safe",
    difficulty: "Moderate",
    placement: "High shelves with strong filtered light",
    soil: "Fast-draining succulent mix",
    fertilizer: "Feed every 6 to 8 weeks lightly",
    temperature: "18°C to 27°C"
  }),
  createPlant({
    id: "aloe-vera",
    name: "Aloe Vera",
    category: "Succulent",
    light: "Bright light",
    size: "Small",
    price: 299,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Aloe%20Vera.jpg",
    description: "A practical windowsill plant known for simple care and clean form.",
    wateringFrequency: "Water only after the soil dries fully, often every 2 to 3 weeks.",
    humidity: "Happy in dry rooms",
    petSafety: "Use caution around pets",
    difficulty: "Easy",
    placement: "Sunny windowsills",
    soil: "Cactus or succulent mix",
    fertilizer: "Feed sparingly in warm months",
    temperature: "18°C to 30°C"
  }),
  createPlant({
    id: "philodendron-birkin",
    name: "Philodendron Birkin",
    category: "Statement Plant",
    light: "Bright indirect light",
    size: "Medium",
    price: 849,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Philodendron.jpg",
    description: "Cream-striped leaves that make each plant look slightly unique.",
    wateringFrequency: "Water when the top inch or two of soil feels dry.",
    humidity: "Prefers medium to high humidity",
    petSafety: "Not pet safe",
    difficulty: "Easy",
    placement: "Bright shelves and side tables",
    soil: "Well-draining aroid mix",
    fertilizer: "Feed monthly in the growing season",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "anthurium-red",
    name: "Red Anthurium",
    category: "Flowering",
    light: "Bright indirect light",
    size: "Medium",
    price: 699,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Anthurium%20andraeanum.JPG",
    description: "Glossy heart-shaped blooms that add a lively indoor accent.",
    wateringFrequency: "Water when the top inch of soil starts to dry, but keep the root zone lightly moist.",
    humidity: "Prefers higher humidity",
    petSafety: "Not pet safe",
    difficulty: "Moderate",
    placement: "Bright rooms away from direct midday sun",
    soil: "Chunky, airy potting mix",
    fertilizer: "Feed every 4 weeks during blooming months",
    temperature: "18°C to 28°C"
  }),
  createPlant({
    id: "spider-plant",
    name: "Spider Plant",
    category: "Beginner Friendly",
    light: "Medium to bright light",
    size: "Small",
    price: 379,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chlorophytum%20comosum.jpg",
    description: "Arching leaves and baby plantlets make it cheerful and forgiving.",
    wateringFrequency: "Water when the top inch feels dry and avoid letting the pot stay soggy.",
    humidity: "Handles average indoor humidity",
    petSafety: "Pet safe",
    difficulty: "Very easy",
    placement: "Shelves, desks, and hanging planters",
    soil: "Standard indoor potting mix",
    fertilizer: "Feed every 4 to 6 weeks in active growth",
    temperature: "16°C to 29°C"
  }),
  createPlant({
    id: "aglaonema-red",
    name: "Aglaonema Red",
    category: "Foliage",
    light: "Low to medium light",
    size: "Medium",
    price: 689,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Aglaonema%20commutatum%20%28lipstick%29.jpg",
    description: "Color-rich foliage for homes that need a bolder indoor plant.",
    wateringFrequency: "Water when the top inch or two dries out.",
    humidity: "Enjoys medium humidity but adapts well",
    petSafety: "Not pet safe",
    difficulty: "Easy",
    placement: "Low-light bedrooms and reading corners",
    soil: "Well-draining indoor potting mix",
    fertilizer: "Feed monthly in spring and summer",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "english-ivy",
    name: "English Ivy",
    category: "Hanging",
    light: "Bright indirect light",
    size: "Small",
    price: 429,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/English%20ivy%20%2825563313181%29.jpg",
    description: "Classic cascading vines that soften shelves, ledges, and windows.",
    wateringFrequency: "Keep the soil lightly moist and avoid long dry spells.",
    humidity: "Appreciates medium humidity",
    petSafety: "Not pet safe",
    difficulty: "Moderate",
    placement: "Cool bright shelves and hanging planters",
    soil: "Loose, well-draining potting mix",
    fertilizer: "Feed every 4 weeks in spring and summer",
    temperature: "15°C to 26°C"
  }),
  createPlant({
    id: "bird-of-paradise",
    name: "Bird of Paradise",
    category: "Statement Plant",
    light: "Bright light",
    size: "Large",
    price: 1599,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Bird%20of%20Paradise%20%285988366571%29.jpg",
    description: "Tall tropical leaves that instantly turn a room into a statement.",
    wateringFrequency: "Water when the top 2 inches feel dry and increase slightly in brighter seasons.",
    humidity: "Prefers medium to high humidity",
    petSafety: "Use caution around pets",
    difficulty: "Moderate",
    placement: "Bright open rooms with space overhead",
    soil: "Rich but draining potting mix",
    fertilizer: "Feed monthly through spring and summer",
    temperature: "18°C to 30°C"
  }),
  createPlant({
    id: "boston-fern",
    name: "Boston Fern",
    category: "Air Purifying",
    light: "Medium indirect light",
    size: "Medium",
    price: 559,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Boston%20Fern%20%282874221420%29.png",
    description: "Soft feathery fronds with classic fern volume and movement.",
    wateringFrequency: "Keep the soil consistently lightly moist without turning soggy.",
    humidity: "Needs higher humidity",
    petSafety: "Pet safe",
    difficulty: "Moderate",
    placement: "Bathrooms and humid bright corners",
    soil: "Moisture-retentive indoor mix",
    fertilizer: "Feed lightly every 4 weeks in growth season",
    temperature: "16°C to 27°C"
  }),
  createPlant({
    id: "syngonium-pink",
    name: "Pink Syngonium",
    category: "Foliage",
    light: "Bright indirect light",
    size: "Small",
    price: 519,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Syngonium%20podophyllum.jpg",
    description: "Pastel-toned arrowhead leaves for a lighter, softer shelf display.",
    wateringFrequency: "Water when the top inch of soil is dry.",
    humidity: "Prefers moderate humidity",
    petSafety: "Not pet safe",
    difficulty: "Easy",
    placement: "Bright desks and shelves with filtered sun",
    soil: "Airy indoor mix",
    fertilizer: "Feed monthly in spring and summer",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "parlor-palm",
    name: "Parlor Palm",
    category: "Pet Friendly",
    light: "Medium indirect light",
    size: "Medium",
    price: 729,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chamaedorea%20elegans%20%2820144031253%29.jpg",
    description: "A soft, graceful palm that fits apartments and calmer corners.",
    wateringFrequency: "Water when the top inch dries out and reduce in cooler months.",
    humidity: "Likes moderate humidity",
    petSafety: "Pet safe",
    difficulty: "Easy",
    placement: "Apartments, bedrooms, and reading nooks",
    soil: "Well-draining palm mix",
    fertilizer: "Feed every 6 weeks in the growing season",
    temperature: "18°C to 27°C"
  }),
  createPlant({
    id: "baby-rubber-plant",
    name: "Baby Rubber Plant",
    category: "Desk Plant",
    light: "Bright indirect light",
    size: "Small",
    price: 489,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Peperomia%20obtusifolia%203zz.jpg",
    description: "Compact glossy foliage for desks, side tables, and bright shelves.",
    wateringFrequency: "Water when the top inch of soil has dried.",
    humidity: "Comfortable in average indoor humidity",
    petSafety: "Pet safe",
    difficulty: "Very easy",
    placement: "Work desks and compact shelves",
    soil: "Well-draining potting mix",
    fertilizer: "Feed monthly in spring and summer",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "hoya-carnosa",
    name: "Hoya Carnosa",
    category: "Hanging",
    light: "Bright indirect light",
    size: "Small",
    price: 579,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Hoya%20carnosa%20%28wax%20vines%29.jpg",
    description: "Waxy trailing leaves and a patient growth habit that rewards consistency.",
    wateringFrequency: "Let at least the top half of the soil dry before watering.",
    humidity: "Enjoys moderate humidity",
    petSafety: "Pet safe",
    difficulty: "Easy",
    placement: "Bright shelves and hanging corners",
    soil: "Chunky, fast-draining mix",
    fertilizer: "Feed monthly during active growth",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "chinese-money-plant",
    name: "Chinese Money Plant",
    category: "Desk Plant",
    light: "Bright indirect light",
    size: "Small",
    price: 539,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pilea%20Peperomioides.jpg",
    description: "Round coin-like leaves that instantly make a room feel playful.",
    wateringFrequency: "Water when the top inch becomes dry and rotate weekly for even growth.",
    humidity: "Average indoor humidity is fine",
    petSafety: "Pet safe",
    difficulty: "Easy",
    placement: "Desks and bright windowside shelves",
    soil: "Light, well-draining indoor mix",
    fertilizer: "Feed monthly in spring and summer",
    temperature: "16°C to 27°C"
  }),
  createPlant({
    id: "dracaena-marginata",
    name: "Dracaena Marginata",
    category: "Air Purifying",
    light: "Medium to bright light",
    size: "Large",
    price: 949,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dracaena%20Marginata.jpg",
    description: "Slim upright canes with spiky foliage for modern interiors.",
    wateringFrequency: "Water when the top 1 to 2 inches are dry, then drain well.",
    humidity: "Adapts to average humidity",
    petSafety: "Not pet safe",
    difficulty: "Easy",
    placement: "Modern living rooms and offices",
    soil: "Well-draining potting mix",
    fertilizer: "Feed every 6 weeks during growth months",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "nerve-plant",
    name: "Nerve Plant",
    category: "Bathroom Friendly",
    light: "Medium indirect light",
    size: "Small",
    price: 429,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Nerve%20plant%20%28Fittonia%20albivenis%29.jpg",
    description: "A humidity-loving plant with vivid veined leaves and compact growth.",
    wateringFrequency: "Keep the soil lightly moist and never let it stay dry too long.",
    humidity: "Needs higher humidity",
    petSafety: "Pet safe",
    difficulty: "Moderate",
    placement: "Bathrooms and terrariums",
    soil: "Moisture-holding but airy potting mix",
    fertilizer: "Feed lightly every 4 weeks in active growth",
    temperature: "18°C to 26°C"
  }),
  createPlant({
    id: "croton-petra",
    name: "Croton Petra",
    category: "Statement Plant",
    light: "Bright light",
    size: "Medium",
    price: 839,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Codiaeum%20variegatum%2001.JPG",
    description: "Bold color-rich foliage for sunny corners that need drama.",
    wateringFrequency: "Water when the top inch begins to dry and avoid sudden routine changes.",
    humidity: "Prefers moderate to high humidity",
    petSafety: "Not pet safe",
    difficulty: "Moderate",
    placement: "Sunny corners with strong filtered light",
    soil: "Rich, well-draining indoor mix",
    fertilizer: "Feed every 4 weeks during active growth",
    temperature: "18°C to 29°C"
  }),
  createPlant({
    id: "norfolk-island-pine",
    name: "Norfolk Island Pine",
    category: "Indoor",
    light: "Bright indirect light",
    size: "Large",
    price: 1199,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Norfolk%20Island%20Pine%20%28Araucaria%20heterophylla%29.jpg",
    description: "Soft layered evergreen structure that feels festive year-round.",
    wateringFrequency: "Water when the top inch feels dry and avoid letting the root ball go fully dry.",
    humidity: "Likes moderate humidity",
    petSafety: "Pet safe",
    difficulty: "Moderate",
    placement: "Bright rooms with cooler steady temperatures",
    soil: "Well-draining indoor tree mix",
    fertilizer: "Feed every 6 weeks in spring and summer",
    temperature: "16°C to 26°C"
  })
];

export default plants;
